spring:
  datasource:
    url: jdbc:mysql://47.95.13.241:3306/wechat_users?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: Wsxm@123456
    type: com.alibaba.druid.pool.DruidDataSource
  druid:
    loginUsername: druid
    loginPassword: druid
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml


logging:
  level:
    com.ching.wechatstudy.serviceDao.*: debug
